version: '3'
services:
  pbsenv:
    environment:
      - bootstrap.memory_lock=true
    build: .
    image: centos_pbs_devenv
    hostname: pbs
    container_name: devenv
    volumes:
      - ~/work:/work:cached
    working_dir: /work/forks/openpbs
    privileged: true
    tty: true
    stdin_open: true
    
